SELECT * FROM EMPLOYEES;


-- DDL
-- CREATE

CREATE TABLE TBL_USER(
	USER_NAME VARCHAR2(1000),
	USER_AGE NUMBER
);

-- ALTER
-- 테이블명 수정

ALTER TABLE TBL_USER RENAME TO TBL_MY_USER;

-- 컬럼 추가

ALTER TABLE TBL_MY_USER ADD (USER_GENDER CHAR(4));

-- 컬럼명 수정

ALTER TABLE TBL_MY_USER RENAME COLUMN USER_NAME TO USER_NICKNAME;

-- 컬럼 삭제

ALTER TABLE TBL_MY_USER DROP COLUMN USER_GENDER;

-- 컬럼의 자료형 수정

ALTER TABLE TBL_MY_USER MODIFY (USER_NICKNAME VARCHAR2(500));

SELECT * FROM TBL_MY_USER;

-- TRUNCATE 
-- TRUNCATE 실습을 위해 INSERT 두 개만 때리자!

INSERT INTO TBL_MY_USER
VALUES('포근', 22);

INSERT INTO TBL_MY_USER
VALUES('호뜩이', 22);

SELECT * FROM TBL_MY_USER;

-- 테이블 내용 전부 삭제
TRUNCATE TABLE TBL_MY_USER;

-- 테이블 삭제
DROP TABLE TBL_MY_USER;

--=======================================================

-- 제약조건.

-- 임의 테이블 생성
CREATE TABLE TBL_CAR(
	CAR_ID NUMBER,
	CAR_NAME VARCHAR2(1000),
	CAR_BRAND VARCHAR2(1000),
	CAR_RELEASE_DATE DATE,
	CAR_COLOR VARCHAR2(1000),
	CAR_PRICE NUMBER
);

-- ALTER 문을 이용한 제약조건 추가
ALTER TABLE TBL_CAR ADD CONSTRAINT PK_CAR PRIMARY KEY(CAR_ID);
/*
 ALTER TABLE TBL_CAR : TBL_CAR 테이블을 수정하겠다.
 ADD CONSTRAINT : 제약 조건을 추가하겠다.
 PK_CAR : 제약 조건 이름 (제약 조건을 삭제할 때 사용)
 PRIMARY KEY(CAR_ID) : PK라는 제약조건을 CAR_ID 컬럼에 부여!
 */

ALTER TABLE TBL_CAR ADD  PRIMARY KEY(CAR_ID);

-- ALTER 문을 이용한 제약 조건 삭제!
ALTER TABLE TBL_CAR DROP CONSTRAINT PK_CAR;

-- 테이블을 만듬과 동시에 해당 컬럼에 PK 제약조건 부여

DROP TABLE TBL_CAR;

-- 제약 조건 추가 OK
-- 제약 조건에 이름은? 랜덤하게 부여
CREATE TABLE TBL_CAR(
	CAR_ID NUMBER PRIMARY KEY,
	CAR_NAME VARCHAR2(1000),
	CAR_BRAND VARCHAR2(1000),
	CAR_RELEASE_DATE DATE,
	CAR_COLOR VARCHAR2(1000),
	CAR_PRICE NUMBER
);

-- 시스템이 부여한 이름을 가지고도 제약 조건 삭제 가능.
ALTER TABLE TBL_CAR DROP CONSTRAINT SYS_C007008;


DROP TABLE TBL_CAR;

-- 제약 조건의 이름을 부여함과 동시에 제약 조건 추가
-- 제약 조건의 이름을 부여하기 위해서는 CONSTRAINT 키워드를 무조건
-- 설정하고 싶은 이름 앞에 명시해준다.
CREATE TABLE TBL_CAR(
	CAR_ID NUMBER CONSTRAINT PK_CAR PRIMARY KEY,
	CAR_NAME VARCHAR2(1000),
	CAR_BRAND VARCHAR2(1000),
	CAR_RELEASE_DATE DATE,
	CAR_COLOR VARCHAR2(1000),
	CAR_PRICE NUMBER
);

DROP TABLE TBL_CAR;

CREATE TABLE TBL_CAR(
	CAR_ID NUMBER,
	CAR_NAME VARCHAR2(1000),
	CAR_BRAND VARCHAR2(1000),
	CAR_RELEASE_DATE DATE,
	CAR_COLOR VARCHAR2(1000),
	CAR_PRICE NUMBER,
	CONSTRAINT PK_CAR PRIMARY KEY(CAR_ID)
);

--=======================================================

-- 실습 
-- 동물 테이블 
-- 고유 번호, 종류, 나이, 먹이 
CREATE TABLE TBL_ANIMAL(
	ANIMAL_ID NUMBER,
	ANIMAL_GENUS VARCHAR2(1000),
	ANIMAL_AGE NUMBER,
	ANIMAL_FOOD VARCHAR2(1000)
);
-- 제약조건 추가(PK)
ALTER TABLE TBL_ANIMAL ADD CONSTRAINT PK_ANIMAL PRIMARY KEY(ANIMAL_ID);

-- 제약 조건 삭제(PK)
ALTER TABLE TBL_ANIMAL DROP CONSTRAINT PK_ANIMAL;

-- 컬럼 추가(성별)
ALTER TABLE TBL_ANIMAL ADD (ANIMAL_GENDER CHAR(4));

-- 컬럼 이름 수정(고유번호)
ALTER TABLE TBL_ANIMAL RENAME COLUMN ANIMAL_ID TO ANIMAL_NAME;

-- 컬럼 삭제(먹이)
ALTER TABLE TBL_ANIMAL DROP COLUMN ANIMAL_FOOD;

-- 컬럼의 자료형 수정
ALTER TABLE TBL_ANIMAL MODIFY(ANIMAL_NAME VARCHAR2(1000));
-- 동물 테이블 삭제
DROP TABLE TBL_ANIMAL;

SELECT * FROM TBL_ANIMAL;

--=======================================================

-- PK의 특징과 FK 부여 방법 및 특징

CREATE TABLE TBL_PRODUCT(
	PRODUCT_NUMBER NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(1000),
	PRODUCT_PRICE NUMBER
);

INSERT INTO TBL_PRODUCT
VALUES (1, '로지텍 K855', 89000);

INSERT INTO TBL_PRODUCT
VALUES (2, '로지텍 G304', 55000);

INSERT INTO TBL_PRODUCT
VALUES (2, '팜레스트', 22000); -- PK가 중복이라서 에러가 발생함.

INSERT INTO TBL_PRODUCT
VALUES (3, '팜레스트', NULL); -- NULL도 값이기에 값으로 사용할 수 있다. (값이 없음을 나타내는 값)

INSERT INTO TBL_PRODUCT
VALUES (NULL, '두루마리 휴지', 25000); -- PK는 NULL을 넣을 수 없다.

SELECT * FROM TBL_PRODUCT;

--=======================================================
-- FK 

CREATE TABLE TBL_SCHOOL(
	SCHOOL_NUMBER NUMBER,
	SCHOOL_NAME VARCHAR2(500),
	CONSTRAINT PK_SCHOOL PRIMARY KEY(SCHOOL_NUMBER)
);

CREATE TABLE TBL_STUDENT(
	STUDENT_NUMBER NUMBER,
	STUDENT_NAME VARCHAR2(500),
	STUDENT_AGE NUMBER,
	SCHOOL_NUMBER NUMBER,
	CONSTRAINT PK_STUDENT PRIMARY KEY(STUDENT_NUMBER),
	CONSTRAINT FK_STUDENT FOREIGN KEY(SCHOOL_NUMBER)
	REFERENCES TBL_SCHOOL(SCHOOL_NUMBER)
);


-- 직접 데이터를 삽입하면서
-- 어떤 식으로 동작하는지 알아보도록 하자!

INSERT INTO TBL_SCHOOL
VALUES(1, '로지텍 고등학교');

INSERT INTO TBL_SCHOOL
VALUES(2, '레이저 고등학교');

INSERT INTO TBL_SCHOOL
VALUES(3, '앱코 고등학교');

SELECT * FROM TBL_SCHOOL;


-- 학생 테이블에 INSERT 진해

INSERT INTO TBL_STUDENT
VALUES(1, '류호근', 22, 1);

INSERT INTO TBL_STUDENT
VALUES(2, '홍길동', 22, 1);

INSERT INTO TBL_STUDENT
VALUES(3, '장보고', 22, 2);

INSERT INTO TBL_STUDENT
VALUES(4, '강감찬', 22, 4); -- FK인 SCHOOL_NUMBER가 존재하지 않는 값을 저장해서 에러 발생

SELECT * FROM TBL_STUDENT;

--=======================================================

-- 기타 제약 조건들.
DROP TABLE TBL_STUDENT;

CREATE TABLE TBL_STUDENT(
	STUDENT_NUMBER NUMBER PRIMARY KEY,
	STUDENT_ID VARCHAR2(500) CONSTRAINT UK_STUDENT UNIQUE,
	STUDENT_NAME VARCHAR2(500),
	STUDENT_MAJOR VARCHAR2(500),
	STUDENT_GENDER CHAR(1) DEFAULT 'W' NOT NULL 
   	CONSTRAINT CHECK_GENDER CHECK(STUDENT_GENDER IN ('M', 'W'))
);

INSERT INTO HR.TBL_STUDENT
(STUDENT_NUMBER, STUDENT_ID, STUDENT_NAME, STUDENT_MAJOR, STUDENT_GENDER)
VALUES(1, 'KIM', '김진수', '호텔조리', 'M');

INSERT INTO HR.TBL_STUDEN
(STUDENT_NUMBER, STUDENT_ID, STUDENT_NAME, STUDENT_MAJOR, STUDENT_GENDER)
VALUES(1, 'KIM', '홍길동', '컴공', 'M'); -- UK 중복으로 인해 에러

INSERT INTO HR.TBL_STUDENT
(STUDENT_NUMBER, STUDENT_ID, STUDENT_NAME, STUDENT_MAJOR, STUDENT_GENDER)
VALUES(2, 'GILDONG', '홍길동', '컴공', 'M'); -- 아이디를 바꾸니 잘 들어감.

INSERT INTO HR.TBL_STUDENT
(STUDENT_NUMBER, STUDENT_ID, STUDENT_NAME, STUDENT_MAJOR)
VALUES(3, 'CHUNHYANG', '성춘향', '데이터사이언스');

INSERT INTO HR.TBL_STUDENT
(STUDENT_NUMBER, STUDENT_ID, STUDENT_NAME, STUDENT_MAJOR, STUDENT_GENDER)
VALUES(4, 'GATSBY', '개츠비', '재벌', 'K'); -- CHECK 제약 조건에 위배되어 에러 발생


SELECT * FROM TBL_STUDENT;



