SELECT * FROM EMPLOYEES;

-- 관계를 맺은 테이블의 DML

SELECT * FROM TBL_PHONE;
SELECT * FROM TBL_CASE;

-- UPDATE 
UPDATE TBL_PHONE 
SET PHONE_SERIAL_NUMBER = 'S23-444'
WHERE PHONE_SERIAL_NUMBER = 'S23-001';
-- 자식에서 참조하고 있는 PK 값의 수정은 기본적으로 막혀있다.
-- 일반적으로 부모 테이블의 PK를 수정하는 것은 권장하지 않는다.
-- 그 이유는 일관성을 손상시키고, 무결성에 위배 될 수 있기 때문이다.
-- 하지만, 필요에 따라서 수정해야할 때도 있기 때문에,
-- 아래의 방법을 알려드립니다.


-- 1. 
-- 참조중인 값을 NULL로 변경 후 수정

UPDATE TBL_CASE  
SET PHONE_SERIAL_NUMBER = NULL 
WHERE PHONE_SERIAL_NUMBER = 'S23-001';
-- 참조중인 자식 테이블의 FK중, 수정하려는 부모 테이블의 값인 친구들을 임시로 NULL로 바꿔준다. 

UPDATE TBL_PHONE 
SET PHONE_SERIAL_NUMBER = 'S23-444'
WHERE PHONE_SERIAL_NUMBER = 'S23-001';

UPDATE TBL_CASE  
SET PHONE_SERIAL_NUMBER = 'S23-444' 
WHERE PHONE_SERIAL_NUMBER IS NULL;
-- UPDATE(수정)을 하기 위해선 위에 있는 것들이 한 세트이기 때문에 적어줘야 된다.
-- 'S23-001'을 NULL로 바꾸고 'S23-444'로 바꿔줌 -> 'S23-444'를 IS NULL로 바꿔주어 TBL_CASE에 추가해준다. (은근 번거로움)

-- 2. 
-- 부모에 임의의 값을 INSERT 하고
-- 자식 FK 를 수정한 후에 진행한다.
INSERT INTO HR.TBL_PHONE
(PHONE_SERIAL_NUMBER, PHONE_COLOR, PHONE_SIZE, PHONE_PRICE, PHONE_PRODUCTION_DATE, PHONE_SALE)
VALUES('111', '', 0, 0, '', 0);

UPDATE TBL_CASE 
SET PHONE_SERIAL_NUMBER = '111'
WHERE PHONE_SERIAL_NUMBER = 'S23-002'; -- 부모에 111 없음 

UPDATE TBL_PHONE
SET PHONE_SERIAL_NUMBER = 'S23-222'
WHERE PHONE_SERIAL_NUMBER = 'S23-002'; -- 자식에서 참조하고 있는 값이 있기에 에러

UPDATE TBL_CASE
SET PHONE_SERIAL_NUMBER = 'S23-222'
WHERE PHONE_SERIAL_NUMBER = '111';

DELETE FROM TBL_PHONE
WHERE PHONE_SERIAL_NUMBER = '111';

SELECT * FROM TBL_PHONE;
SELECT * FROM TBL_CASE;

-- [실습]
/*
 * TBL_MEMBER, TBL_BOOK 활용
 * 회원 정보 추가 (3개 이상)
 * 책 정보 추가 (3개 이상)
 * 책 대여 하기
 * 책 대여한 회원 번호 수정
 * 회원 삭제
 */

/*
SELECT * FROM TBL_MEMBER;
SELECT * FROM TBL_BOOK;

INSERT INTO HR.TBL_MEMBER
(MEMBER_ID, MEMBER_NAME, MEMBER_AGE, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES(123, '홍길동', 20, '010_1234_5678', '서울');

INSERT INTO HR.TBL_MEMBER
(MEMBER_ID, MEMBER_NAME, MEMBER_AGE, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES(234, '이순신', 23, '010_4312_7893', '경기');

INSERT INTO HR.TBL_MEMBER
(MEMBER_ID, MEMBER_NAME, MEMBER_AGE, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES(456, '김민수', 25, '010_3653_6588', '인천');



INSERT INTO HR.TBL_BOOK
(BOOK_ID, BOOK_NAME, BOOK_GENRE, MEMBER_ID)
VALUES(3567, 'JAVA', 'IT', 123);

INSERT INTO HR.TBL_BOOK
(BOOK_ID, BOOK_NAME, BOOK_GENRE, MEMBER_ID)
VALUES(4856, '추리소설', '추리', 234);

INSERT INTO HR.TBL_BOOK
(BOOK_ID, BOOK_NAME, BOOK_GENRE, MEMBER_ID)
VALUES(5861, '인문학_책', '인문학', 456);
*/

SELECT * FROM TBL_MEMBER;
SELECT * FROM TBL_BOOK;

-- 강사님께서 적은 코드 

-- [실습]
/*
   TBL_MEMBER, TBL_BOOK 활용!
   
   회원 정보 추가 (3개 이상)
   책 정보 추가 (3개 이상)
   회원 이름 수정
   책 대여 하기
   책 대여한 회원 번호 수정
   회원 삭제
   
 
--회원 정보 추가 (3개 이상)
INSERT INTO TBL_MEMBER
VALUES(1, '류호근', 22, '010-1111-1222', '수원시 장안구');

INSERT INTO TBL_MEMBER
VALUES(2, '홍길동', 23, '010-2222-2222', '수원시 장안구');

INSERT INTO TBL_MEMBER
VALUES(3, '강감찬', 25, '010-3333-3333', '수원시 장안구');

--   책 정보 추가 (3개 이상)
INSERT INTO HR.TBL_BOOK
(BOOK_ID, BOOK_NAME, BOOK_GENRE)
VALUES(101, '셜록 홈즈', '추리');

INSERT INTO TBL_BOOK
(BOOK_ID, BOOK_NAME, BOOK_GENRE)
VALUES(102, 'DBMS 완전 정복', 'IT');

INSERT INTO TBL_BOOK
(BOOK_ID, BOOK_NAME, BOOK_GENRE)
VALUES(103, '그리고 아무도 없었다', '추리');

--   회원 이름 수정
UPDATE TBL_MEMBER 
SET MEMBER_NAME = '스펀지밥'
WHERE MEMBER_ID = 1;

--   책 대여 하기
UPDATE TBL_BOOK 
SET MEMBER_ID = 1
WHERE BOOK_ID = 101;

UPDATE TBL_BOOK 
SET MEMBER_ID = 1
WHERE BOOK_ID = 102;

UPDATE TBL_BOOK 
SET MEMBER_ID = 3
WHERE BOOK_ID = 103;

--   책 대여한 회원 번호 수정
UPDATE TBL_BOOK 
SET MEMBER_ID = NULL
WHERE MEMBER_ID = 1;

UPDATE TBL_MEMBER
SET   MEMBER_ID = 49
WHERE MEMBER_ID = 1;

UPDATE TBL_BOOK 
SET MEMBER_ID = 49
WHERE MEMBER_ID IS NULL;

--   회원 삭제
UPDATE TBL_BOOK 
SET MEMBER_ID = NULL
WHERE MEMBER_ID = 49;

DELETE FROM TBL_MEMBER
WHERE MEMBER_ID = 49;

SELECT * FROM TBL_MEMBER;
SELECT * FROM TBL_BOOK;
*/

--=================================================

-- SEQUENCE
-- 회원과 책 정보를 INSERT할 때 
-- PK를 직접 지정하는 것이 아닌, 시퀀스로 받아올거예요!

TRUNCATE TABLE TBL_BOOK; 
DELETE FROM TBL_MEMBER;
DELETE FROM TBL_BOOK;
-- 시퀀스 생성

CREATE SEQUENCE SEQ_BOOK;
CREATE SEQUENCE SEQ_MEMBER;

-- 시퀀스를 사용해서 데이터 붙혀넣기

--회원 정보 추가 (3개 이상)
INSERT INTO TBL_MEMBER
VALUES(SEQ_MEMBER.NEXTVAL, '류호근', 22, '010-1111-1222', '수원시 장안구');

INSERT INTO TBL_MEMBER
VALUES(SEQ_MEMBER.NEXTVAL, '홍길동', 23, '010-2222-2222', '수원시 장안구');

INSERT INTO TBL_MEMBER
VALUES(SEQ_MEMBER.NEXTVAL, '강감찬', 25, '010-3333-3333', '수원시 장안구');

SELECT * FROM TBL_MEMBER;

--   책 정보 추가 (3개 이상)
INSERT INTO HR.TBL_BOOK
(BOOK_ID, BOOK_NAME, BOOK_GENRE)
VALUES(SEQ_BOOK.NEXTVAL, '셜록 홈즈', '추리');

INSERT INTO TBL_BOOK
(BOOK_ID, BOOK_NAME, BOOK_GENRE)
VALUES(SEQ_BOOK.NEXTVAL, 'DBMS 완전 정복', 'IT');

INSERT INTO TBL_BOOK
(BOOK_ID, BOOK_NAME, BOOK_GENRE)
VALUES(SEQ_BOOK.NEXTVAL, '그리고 아무도 없었다', '추리');

SELECT * FROM TBL_BOOK;

-- 관계를 맺은 테이블 간의 데이터의 삭제!

SELECT  * FROM TBL_MEMBER;
SELECT  * FROM TBL_BOOK;

-- 책 대여하기
UPDATE TBL_BOOK 
SET MEMBER_ID = 1
WHERE BOOK_ID = 1;

UPDATE TBL_BOOK 
SET MEMBER_ID = 1
WHERE BOOK_ID = 2;

UPDATE TBL_BOOK 
SET MEMBER_ID = 3
WHERE BOOK_ID = 3;

-- 자식에서 참조하고 있기 때문에 삭제 불가능!
DELETE FROM TBL_MEMBER
WHERE MEMBER_ID = 1; 

-- 1. 자식에서 해다 FK 값을 NULL로 수정! 

-- 2. 자동으로 부모 PK가 삭제되면 
-- 자식에서 해당 PK 값을 참조하고 있던 행도 함께 삭제!
-- FK 제약조건 뒤에 ON DELETE CASCADE 옵션을 추가함으로써 구현!

-- FK 제약조건 삭제 
ALTER TABLE TBL_BOOK DROP CONSTRAINT FK_BOOK;

ALTER TABLE TBL_BOOK 
ADD CONSTRAINT FK_BOOK FOREIGN KEY(MEMBER_ID)
REFERENCES TBL_MEMBER(MEMBER_ID) ON DELETE CASCADE;

DELETE FROM TBL_MEMBER
WHERE MEMBER_ID = 1;


SELECT * FROM TBL_BOOK;

--=================================================

-- 이미 만들어진 테이블에 NOT NULL 추가 및 삭제
ALTER TABLE TBL_CAR MODIFY CAR_NAME NOT NULL;
ALTER TABLE TBL_CAR MODIFY CAR_NAME NULL;

-- NVL 

SELECT * FROM TBL_BOOK;
SELECT * FROM TBL_MEMBER;

INSERT INTO HR.TBL_BOOK
(BOOK_ID, BOOK_NAME, BOOK_GENRE)
VALUES(SEQ_BOOK.NEXTVAL, '셜록 홈즈', '추리');

INSERT INTO TBL_BOOK
(BOOK_ID, BOOK_NAME, BOOK_GENRE)
VALUES(SEQ_BOOK.NEXTVAL, 'DBMS 완전 정복', 'IT');

INSERT INTO TBL_BOOK
(BOOK_ID, BOOK_NAME, BOOK_GENRE)
VALUES(SEQ_BOOK.NEXTVAL, '그리고 아무도 없었다', '추리');

-- SELECT 는 테이블에 있는 데이터를 가지고 
-- 가상의 테이블을 만드는 것이다.
SELECT BOOK_ID, BOOK_NAME, BOOK_GENRE, NVL(MEMBER_ID, -1)
FROM TBL_BOOK;

SELECT BOOK_ID, BOOK_NAME, BOOK_GENRE, 
	NVL2(MEMBER_ID, '대여 중', '대여 가능') "대여 가능 여부"
FROM TBL_BOOK;

SELECT * FROM PLAYER;














