-- 회원제 게시판 프로젝트
CREATE TABLE TBL_USER(
	USER_NUMBER NUMBER,
	USER_ID VARCHAR2(100) NOT NULL UNIQUE,
	USER_PW VARCHAR2(100) NOT NULL,
	USER_NAME VARCHAR2(100) NOT NULL,
	USER_PHONE VARCHAR2(100) NOT NULL UNIQUE,
	USER_BIRTH DATE,
	USER_RECOMMENDERNUMBER NUMBER,
	CONSTRAINT PK_USER PRIMARY KEY(USER_NUMBER),
	CONSTRAINT FK_USER FOREIGN KEY(USER_RECOMMENDERNUMBER)
	REFERENCES TBL_USER(USER_NUMBER) 
);

-- 프로젝트 전체에 시퀀스 하나만!
CREATE SEQUENCE SEQ_PRO;

INSERT INTO TBL_USER
(USER_NUMBER, USER_ID, USER_PW, USER_NAME, USER_PHONE, USER_BIRTH, USER_RECOMMENDERNUMBER)
VALUES(SEQ_PRO.NEXTVAL, 'goseong', '7777', '온고지신', '010-3333-3333', '2010-04-03', 1);

-- 중복 검사 쿼리문.
SELECT COUNT(USER_ID) FROM TBL_USER
WHERE USER_ID = 'hogeun';

SELECT * FROM TBL_USER;


SELECT * FROM TBL_USER
WHERE USER_NUMBER = 1;

UPDATE TBL_USER 
SET USER_PW =?
WHERE USER_PHONE =?

DELETE 
FROM TBL_USER =?
WHERE TBL_MUMBER =?

-- 내 정보를 보는데, 내가 추천한 사람의 아이디와 이름도 같이 확인! 

SELECT T2.* , T1.USER_ID , T1.USER_NAME 
FROM TBL_USER T2 JOIN TBL_USER T1
ON T1.USER_NUMBER = T2.USER_RECOMMENDERNUMBER
WHERE T2.USER_NUMBER = 21;

SELECT COUNT(USER_RECOMMENDERNUMBER), T2.* , T1.USER_ID, T1.USER_NAME
FROM TBL_USER T1 JOIN TBL_USER T2
ON T1.USER_NUMBER = T2.USER_RECOMMENDERNUMBER 
WHERE T2.USER_NUMBER


SELECT COUNT(*) 
FROM TBL_USER 
WHERE USER_RECOMMENDERNUMBER = 1;

















