CREATE TABLE TBL_MEMBER(
	MEMBER_NUMBER NUMBER,
	MEMBER_ID VARCHAR2(100) NOT NULL,
	MEMBER_PW VARCHAR2(100) NOT NULL,
	MEMBER_NAME VARCHAR2(100) NOT NULL,
	MEMBER_PHONE VARCHAR2(100) NOT NULL,
	MEMBER_GENDER VARCHAR2(1) DEFAULT 'M' NOT NULL,
	MEMBER_REGISTER_DATE DATE NOT NULL , 
	CONSTRAINT CHECK_GENDER CHECK(MEMBER_GENDER IN ('M', 'W')),
	CONSTRAINT PK_MEMBER PRIMARY KEY(MEMBER_NUMBER)	
);

DROP TABLE TBL_MEMBER ;

CREATE TABLE TBL_POST(
	POST_NUMBER NUMBER,
	POST_TITLE VARCHAR2(1000) NOT NULL,
	POST_CONTENT VARCHAR2(1000) NOT NULL,
	POST_VIEWS VARCHAR2(100),
	POST_REGISTER_DATE DATE NOT NULL,
	MEMBER_NUMBER NUMBER,
	CONSTRAINT PK_NUMBER PRIMARY KEY(POST_NUMBER),
	CONSTRAINT FK_POST FOREIGN KEY(MEMBER_NUMBER)
	REFERENCES TBL_MEMBER(MEMBER_NUMBER)
);

	
CREATE TABLE TBL_COMMENT(
	COMMENT_NUMBER NUMBER,
	COMMENT_CONTENT VARCHAR2(1000),
	COMMENT_REGISTER_DATE DATE NOT NULL,
	POST_NUMBER NUMBER,
	MEMBER_NUMBER NUMBER,
	CONSTRAINT PK_COMMENT PRIMARY KEY(COMMENT_NUMBER),
	CONSTRAINT FK_NUMBER FOREIGN KEY(POST_NUMBER)
	REFERENCES TBL_POST(POST_NUMBER),
	CONSTRAINT FK_MEMBER FOREIGN KEY(MEMBER_NUMBER)
	REFERENCES TBL_MEMBER(MEMBER_NUMBER)
);


SELECT * FROM TBL_MEMBER;


INSERT INTO HR.TBL_MEMBER
(MEMBER_NUMBER, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_GENDER, MEMBER_REGISTER_DATE)
VALUES(SEQ_PRO.NEXTVAL, '', '', '', '', 'M' , '');


/*
DROP TABLE TBL_MEMBER CASCADE CONSTRAINT;

CREATE TABLE TBL_MEMBER(
   MEMBER_NUMBER NUMBER,
   MEMBER_ID VARCHAR(100),
   MEMBER_PW VARCHAR(100),
   MEMBER_NAME VARCHAR(100),
   MEMBER_PHONE VARCHAR(100), 
   MEMBER_GENDER VARCHAR(100) DEFAULT 'W',
   MEMBER_REGISTER_DATE DATE,
   CONSTRAINT PK_MEMBER PRIMARY KEY(MEMBER_NUMBER),
   CONSTRAINT CHECK_MEMBER_GENDER CHECK (MEMBER_GENDER IN ('W', 'M'))
);

CREATE TABLE TBL_POST(
  POST_NUMBER NUMBER,
  POST_TITLE VARCHAR(500),
  POST_CONTENT VARCHAR(500),
  POST_VIEWS NUMBER,
  POST_REGISTER_DATE DATE,
  MEMBER_NUMBER NUMBER,
  CONSTRAINT PK_POST PRIMARY KEY(POST_NUMBER),
  CONSTRAINT FK_POST FOREIGN KEY(MEMBER_NUMBER)
  REFERENCES TBL_MEMBER(MEMBER_NUMBER)
);

CREATE TABLE TBL_COMMNET(
  COMMENT_NUMBER NUMBER,
  COMMENT_CONTENT VARCHAR(100),
  COMMENT_REGISTER_DATE DATE,
  POST_NUMBER NUMBER,
  MEMBER_NUMBER NUMBER,
  CONSTRAINT PK_COMMENT PRIMARY KEY(COMMENT_NUMBER),
  CONSTRAINT FK_COMMENT FOREIGN KEY(POST_NUMBER)
  REFERENCES TBL_POST(POST_NUMBER),
  CONSTRAINT FK_COMMENT2 FOREIGN KEY(MEMBER_NUMBER)
  REFERENCES TBL_MEMBER(MEMBER_NUMBER)
);

INSERT INTO HR.TBL_MEMBER
(MEMBER_NUMBER, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_GENDER, MEMBER_REGISTER_DATE)
VALUES(SEQ_PRO.NEXTVAL, 'yuna', '5252', '이유나', '4021', 'W', sysdate);
-- 82-85
INSERT INTO HR.TBL_POST
(POST_NUMBER, POST_TITLE, POST_CONTENT, POST_VIEWS, POST_REGISTER_DATE, MEMBER_NUMBER)
VALUES(SEQ_PRO.NEXTVAL, '벚꽃엔딩', '봄바람 휘날리며~', 9, sysdate, 84);
-- 86-89

SELECT * FROM TBL_POST;

INSERT INTO HR.TBL_COMMNET
(COMMENT_NUMBER, COMMENT_CONTENT, COMMENT_REGISTER_DATE, POST_NUMBER, MEMBER_NUMBER)
VALUES(SEQ_PRO.NEXTVAL, '굽네 볼케이노 먹어~', sysdate, 87, 82);
-- 90-93



-- 여자 회원이 몇 명인지 알기 위해서 짜야하는 SQL
SELECT COUNT(*) 
FROM TBL_MEMBER
WHERE MEMBER_GENDER = 'W';

-- 댓글의 정보를 가지고 올건데, 누가 적었는지를 보고 싶어요!
-- member pk 가 전달됐을 때, 그 친구의 이름이 뭐고, 어떤 댓글들을 작성했는지 확인!
SELECT T.*, M.MEMBER_NAME 
FROM TBL_MEMBER M JOIN TBL_COMMNET T
ON M.MEMBER_NUMBER = T.MEMBER_NUMBER
AND T.MEMBER_NUMBER = 82;

-- 검색 쿼리문 만들기
SELECT *
FROM TBL_POST
WHERE POST_TITLE LIKE '%?%'
OR POST_CONTENT LIKE '%?%';

-- 테이블 3개 조인하는 또 다른 방법
SELECT * -- 원하는 컬럼을 골라 조회하고, 거기에 맞는 DTO 를 선언하면 된다.
FROM TBL_MEMBER M, TBL_POST P, TBL_COMMNET C
WHERE M.MEMBER_NUMBER = P.MEMBER_NUMBER 
AND   P.POST_NUMBER = C.POST_NUMBER
AND M.MEMBER_NUMBER = 82;
*/




































